# Generated by Django 6.1 on 2026-08-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'დაბალი'), (2, 'საშუალო'), (3, 'მაღალი')], default=2),
        ),
    ]
